apiVersion: v1
kind: Secret
metadata:
    name: evolution-runtime-auth
    namespace: business
type: Opaque
data:
    DATABASE_CONNECTION_URI: ENC[AES256_GCM,data:GU535gubA4C5YeFc1FbxnSIt2lZ8igTWc02vOuLaTCK1qE9qN170xG3mJcPSCXdOrp+IHFVX267B6DPOYMYtK0HB95p2homGLK/+I2jKFeTpp5aWBeIHadzLgHnoOYtB6fMqT9eaaSrq8GzP4cjx48XM3RXJyCY0GrTuG1wk06JK9B9nT1GfUVDHxzl9NGgbMaJ9byK9ygaFOBPk5OwX3ML3Qp36Ua2nMR0Wir8kwg9V05RVBd95f7vfq8/mBzY20bUWJaJ6CWCSDSzTbE3VmHEZta7CUEs41sXA+Q==,iv:kOcDfoOdz4ZadhW/E5s6/oaGJJFRtGz2CWQMYcycuCQ=,tag:TRtlhxJQFxk5MCcl6HParA==,type:str]
    DATABASE_BOUNCER_CONNECTION_URI: ENC[AES256_GCM,data:LOtJernQVL9MT04uA3aPSQs8aOYGVuGGNcazYu3MYmvc1WOMfmKsE4Relqac7ZWT6zC3f8QT1sf5WHvMXdH4vEKkIpRIvTMG/O3Kbqy08YEUoU+zs0NrmYm6YJFrK3lj8N+jQQUaEhhP5Y+I1rWAYg80kxylqVBawdSAZF3mbazDelwot5BZgoC0YDGNu7EI6e70/JyXzCzxYV44JI/JVqgrFhHP75dXnSdg6G8lvPlSGa2LryZHHuMiS3nSv5MvRbqTyJIaRX5pxZW8t0QXfGuZ+veBvyyB4eLbMytqpO/rAVzaRNn0fLo6PMK0YtoYOVhtFQ==,iv:3lpfgy0lOzX0wGkoQ5ob4ihpzVeL0OHO9QSBPjI/l2M=,tag:UVBSoZgJ+koePmhBd49w4w==,type:str]
    CACHE_REDIS_URI: ENC[AES256_GCM,data:1TdzoTtAgtYlqXE9reCYjajK4gxCzidlCgPoDZ8BRmJ1uxuZ9W6bZ0csjFrsXL0sgdSl1Crj4ToWm7rIDCQgOysYvFoFGv3WBKnTPebsWh60ig46rzW6xiOCJesnOPKjvH5Pv8IhlPDtgWX8,iv:xxs2tX5HcE0rGiTTVHvC+JGolJVlNTyVnt98C6wCSm4=,tag:UqwkG1KGPUtSp1VO1qYiQA==,type:str]
    AUTHENTICATION_API_KEY: ENC[AES256_GCM,data:WRE2VlCCvH1YO7X6Sh3pFfmtg2QcuqkIEJygIgnfCuDP9JXpzlcO1XNr7k08KBJoSYxskGrU6grF2EQA2QMU95BCQtfdZ/I7shuS1NYMysASIob3djTQWQ==,iv:zDBCMSe0pNqI1l2BDn+WNUFk+v9S0PrhdRiulZp0xKg=,tag:0Q9tzIjrQxHqFnj8aPWa2g==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:nv2hgGVZecaTqGPWy5Tv39T2Rn8=,iv:RDA1hxMtQab9eu/Bvymgg1Lncg7alCk6MZKD2WM8yx8=,tag:pMWdyH7k3ViOmC7uZVTCtA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:jmhznmIoMIs6VZBrJKeGKoOQ3KrPRm9FUrrCLYbihiI6Ep8CT+ZWRl16M4di9R3GNYn6utzNyYs=,iv:rCu/87kViPvjHJ2ZeUhoe8fJU3lcwbBkwcrhQjB6LOA=,tag:Tn5CQl6AhJ0DaTFWsjWYKA==,type:str]
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUldnNlVtZHkwVnB1RTEy
            cmo1K1NleTE3c1Y5NXhpNm40S3Z2d3RvcldJCmVXOFpMYzhYWnRmMlIxYzJsRytO
            eDVkQ2xSczU2ZzlZQnd0MERuZytlNGMKLS0tIG1qUXdzQ2tPVHJTdEVZUWswbFFR
            TzJsVmprZ25WUGpIRDB5VlZSa3c3R1EKjPa5ov6D+3RCs1c5HljaVxuZiB54ENdW
            qCRvUH42mHl6haIUjvKUJ0nNGGqIi9JFZe7icpwLft0y+v8W6pJBZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T15:24:50Z"
    mac: ENC[AES256_GCM,data:npsgOqbP+/Qz9SpQ684gWrXhiNqLXb+iOlABiBo9xpBkYYUl3VNjf59lbI78qkBls/MvvnlaBN6Wl/cy5qOQaXIaFJ+5s+TiO+sUQLrYh2B2ofdTIehkMXBP3jHsLs60dhXmzz5N0qe9ka4HaIgFESEo5E5BGeyH9qdApVJI4Jk=,iv:UzoeVOXxXd5sDOQpdu1guEzIhZVXVAHl+85GKCmgmRA=,tag:NnjMRf6PEmShzNJItFalYA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.12.2
