apiVersion: v1
kind: Secret
metadata:
    name: evolution-runtime-auth
    namespace: business
type: Opaque
data:
    DATABASE_CONNECTION_URI: ENC[AES256_GCM,data:qsZFV7VgAijz4lWNOa8qLEazvofFpEl/okExIi9Mpv0DGPgjD4idQ68TqaCW0t4B93oKrxEaTyiAuRtJNcTbR3ZoS8tHBn/H8Xl5afrLsiZCrgWKof1K7hatwh72YB3iDZq0YStD9ZWTJP9Pd226Wkk8STXiGWHDH5Dgt8xYnqyfQ0Tw6YGK0pyMvJQETPOcJhljL5kj8aTg3d3iW+X7ZYOEU00wJaRPSryUi27KYYSFS8I0pS6GBOl8/80nkowlUYB4sO7rxL8zlbr6LJR78UWSsZW1lndX69YqIw==,iv:QJ7LrLCAXBETEOhQAlBlQ0QN/xwQGDYptF0IL/a6quE=,tag:fruWPzeWty80OedSd9foGA==,type:str]
    DATABASE_BOUNCER_CONNECTION_URI: ENC[AES256_GCM,data:C3gJ2Z88vgvGa1+72ta9CZIcKL8H9l1Mm4sdpUFHepCjZAAMJOcUq+ZnSztsBBQMYDTTQMIv7Xage8a0RO5pixCCUvIRSzyG5yCWIcnBQf7m/4BCeun7+/X23vJZByT1vSBrfsA3gSMW69uTO7CoKG3tvdwELkpzQume1aMn7q8bLCXBxk3rczD05FCUO/0NBt0tbjjpbTnItHYxlYOO/MNKYo1j9q+XatsqNsbKvXFo1WDa0BgWIaPkiTTUEfz6b6z1gtLA1PNDs1iZ5r5Mji4udRAz5HufTRfoyb1XfyZEBRFghtjhPXpFaa8EVUJYqHm0sw==,iv:1qcSrx8sfOnsT/Ij3i0I/TAcHbkSlucRFjk0B3EDE6A=,tag:r+e1WZMi3jCNOF+zkBsH4w==,type:str]
    CACHE_REDIS_URI: ENC[AES256_GCM,data:TPv7Tqtp/plfG3pfrTZQmdd3s8vsHsfilTeTx7CN69iabpr3ftavVkUf6CkFjC8ww6AlA9Gh8hDz7c3s5lYDvcsIdaatseP4GEOcHMPRFIoROMD8UbdyMKyqZXbV0uzYJwTrR027/262FaFX,iv:DCzsUlhGhBBI30DxR957tWJ8VJqHoC5NqgrSEAhlrZs=,tag:dNSuoiQg7TqDJ22XoqVKjQ==,type:str]
    AUTHENTICATION_API_KEY: ENC[AES256_GCM,data:/uS0AGwceA4ATYssUrHi4xbo2oxiXbc6Oqk0vZ8dp1Jl3AG6WdxM++9sVgQ9k1AhEn+wzBLFaXwfsPRrOEUBVwoEqhuy5RiMTDLpDPzer8RuHMBjPoWy2A==,iv:p20R8bYt1u3HrVg0pFFp8tJTjsJII/WjmumLjNvp+RI=,tag:yP1dVWKlZHcldIwkxrVPdw==,type:str]
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiallPeGNQdnA5V0QxT3hl
            eVdBNE4zL1owY1lrOWV5MUxTOFg1TGltOVJZCjNKZzZyZVlLQVlZQjRKb2dWaGM4
            dnVNaXlqOWF4RFhJemJDc1NreGl1RFUKLS0tICtldlNLWW5GU3Bqa2liTHNKZXho
            enNxczBxUzdaNU5iRTRGRzAxc1d3TDQK09miUZwLJRFLCTnf5MoXjWaaHrPqv8bx
            aXJK14+VVRGx8oP9/2528Yp2Ia3GOo60BPKwI4OR2Vr5eeyBwLXQaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T14:40:10Z"
    mac: ENC[AES256_GCM,data:9ndSH+pnkhGdZg5F5p/jOtT2wmuLGcz47B1Ovp48fYuTZPOOOFc3jpQ+NLr3iyV4dgQHXLO68VKZCr/vJqXSiED75srXftSS0KZFLu4OVQF3YWSkoSJA2n5NP5y055yMfLVr2GdjWT4qaeLtqIz+KpZ1lrLGALL1hAXCPUWEB+w=,iv:I41VEbQ2IL52PSPLZcDtV/Pq2uqN2e6/6aLb2rTVVsw=,tag:CxrRGoXOJ13v480DH0/5tQ==,type:str]
    encrypted_regex: ^(data)$
    version: 3.12.2
