apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:cMpYrfuVzd/748l/Lzg3vGMtvqTcj9XKS9e0j0cj14r9f/2wu+n4y23RrVQeSi4tGZgRQ7lNCH9uWS0b,iv:aiC26D+iaWpAUgnS4XAaYR8J3dlSM0vqF8wwApTQcbc=,tag:2HwuVqPEh77TJKRBTH2xxg==,type:str]
    admin-user: ENC[AES256_GCM,data:ezBkpjSbjLI=,iv:Qqi6i8srOVSsh6x4nNpZkwZZUjIT4hWFMpTJecxz0OQ=,tag:MV9Rl2EkqDu5A0JtejSn/A==,type:str]
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOV3R3UHNZTzIycEtaYzJH
            RDJMcER0N0svY2FlbnlxYmx3bmc3ZitMdFQ4ClNHMGNOWGUvNDZuY1RKUXhSM0lS
            TURlVkY3UWF6bEkwWU1BOURIUVFNUXMKLS0tIHpBMEN5bmVqTVA5c2hRWEJkVFBZ
            L1dKSjYwazJZMlI3M3RoT3l1cm9vRzAKoF4Jy0KgZxrOIMol1Oi4RZvAkP0F4r9K
            vvjpaI0TApaS2S16JY9YV73WPgM4pdI7+aS2MU5RxIXc7zz2hfPofQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T17:03:20Z"
    mac: ENC[AES256_GCM,data:HS1sNTp5mAeK02j/8f3NWKOwSnKQi9gLfFCbkpqdV+eUTVnWviLIMAShMRmwZWXrCeNXPJvujzu+h6qkp/OG5O72LZAGhtroUUqZlEY58csVcMy+iPIyza7Pk6+NeDhBnSyvUyj+DIv91FLj1F0Pa0/48mazn4eghg8MOPFlzNQ=,iv:MXgojns6rBzcQABmozTvTvo/cc+e34ldXuYkXK0mSQ0=,tag:vVTqTcmn4IjtzzOxDWeiBg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.12.2
