apiVersion: v1
data:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:FMT+1zwtStM6W+/NuqUIKVdFf1mBa6BUI1M/KbbFtdp7gefLTs6CvClBsLORfSghwbcn+xYJxVUizngFBJetYw==,iv:7EBDY+cqSXqYMGYgpk0Uu7mfKjcdD8qhVceMyiAuACg=,tag:pus0I0V4pfycA/lA+Oj1ZA==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:hcXZIcwkYIQNkx9k,iv:e0yZf/b+8/te+uSMwAqy6XZtCzh+gWo6svQsLgjV2Tw=,tag:3bvtjJa/d97LQDRSywfIFA==,type:str]
kind: Secret
metadata:
    name: grafana-alerting-contact
    namespace: monitoring
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TmxuV0pveUN5b0lCVzdh
            UngwNjhmT3FpVjhsVWY2czdwNXo2RHdmUFRZCjlXa0pBN045MG4yQ3d5Q1VaUEln
            WDNvOFpDZVlhYWJCQWpKeEZnVnY0TVUKLS0tIGx1dk9EZEM2Rmx4Ui9SWmMrMHVy
            cldMbVlSaEZ4eUZwMzgrMU42Nk1iYmMKU8lDnN/W1JWsXTi6QgIpwUrOhvq6X/UN
            SvcmrJcVbCY2lsv5uBpQsBMB1jtPcmjj01Qn+XsaKDtP61KOIfck4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T18:43:27Z"
    mac: ENC[AES256_GCM,data:oJSo9utCmLNVeXH9OkiSeXzkBxPT3EJFuk/6a8wacRC0fFyVFuUBMiZAn1arPmCewuNEelG5/Ih4hD8teezv/GlzMVZ7OGf7eCi6/hLPw6IOi0wiS5lryhKa+EBoRUo34/6pzaet/2whihrJ2VmlLI5vALYcIGqffwD23vAgeVU=,iv:FpGwHQGv0qlFHGYDEOMc3QreiRcz5tGOCKmt8udUhmg=,tag:8QrhRj4WaB8PgE4EjZjhEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
