apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:TOOpUbGNwT+y7keUeckV4L40xmNg/nrlSk2yohieP2VibOg3G1z5fLRB4lXUTLh3RDIbdYiStI9P0m3s,iv:ZZ4z2TgUhisyRQzuL6ennCcTdspvVpygBxUZ4oIrX1U=,tag:QiFp0sKnpmESAHpedSMS2g==,type:str]
    admin-user: ENC[AES256_GCM,data:Ansy8rgaaYM=,iv:FanV0g6vkLwz6xdYhuwLxpHgWGmu8Dfba66mEuzTB8M=,tag:ftznFbdsSoR/Op8ZcRRYtg==,type:str]
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNFhsMlQ0NVd5L1JVS0ZS
            Q0Y0YnBEOEUzODFQMlUzTTZhdC90andwRmdNCnJzdFpPOVVxWjZGcHgxTU9SdG5L
            VFEvdU1CQUtUWnp3bkVsQWMxTzc3NGMKLS0tIEdWNkNqVlRiRlh4bUxwM0UvZ1d0
            NTZUNlI2Q0tOa0N6OFZHK2lzV2dWZjQKLVPCqKdgkLpM9jC3Xu2qAMA/60hvecza
            SrKqYewy8BwvGL2ZDmQ9g4da5JZhDYtjHlOLDAMJwN94EWCOVOL2cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T17:23:59Z"
    mac: ENC[AES256_GCM,data:zkVOIaZKL0eNTXPYthiErstv5wqDEbQBHifK7dnlPPvUuHYzrmKcRZHFfs5/OFszxAZoxcWwgpKKnOmJ5NTmZuwjvV4XcbDSJLzGgi+yekhRtUB5HSEpncbs3DQ34SBSP+NH1MNhy7xKQnTfOD6B2hsxCPW11ubaNmLuTPrsQCE=,iv:4pDrk6NuWVpJrAz3//cUkb7p/JazLeDaQsex/6hsyZM=,tag:YJgGJy2xiAv/eYBJvSZL5g==,type:str]
    encrypted_regex: ^(data)$
    version: 3.12.2
