apiVersion: v1
kind: Secret
metadata:
    name: sistema-centro-fashion-db-auth
    namespace: business
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:psitUo27afgBDnAW1r5SLYeOmMMmesuw5sdIKIIJOefR4fvhp2c3UsdEqfrwUmlUN5yfCg0B5F/MlnuCvGqm/esyexFZMompkYDv9BwDq6yI8BJd9KovcGVRYTNJXJlF14Do2tZuocFLHt5NOzBkWGbWiA9FAWqjGhF9AkN6Cr+gTS0B0cQElS5yrWzR,iv:8+uAaVgndbFdoBrFJzc/dpXFRQ7nU5fu21BKpSnVjfc=,tag:NfYHiaiI8AURwE/us5yy5A==,type:str]
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRVh0MTdYcW1CVk5HMkNn
            U2FnSDRoQ1BhTFFOMWxUVE4vMU93d2JMUWtjCmtZeWI5UTR1VGEzRS9uclVsa05S
            WVFJQjZ6S1VMZXlvMUtRbEdRZElmTlkKLS0tIDRTL3c5clJkWlk4ZWZZUTFVc2Q1
            Nzd2a3djODdLMDVvaW1kS1VaTjRVRVEK0gAta2prL6R6a1ZBtvEZ0y9iQDDUfiqO
            OJJ//sIpF/tMEVYNNl+UqmwBcOs5uLuuXKYfIEjcVerbDZqBxrXeUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T00:45:45Z"
    mac: ENC[AES256_GCM,data:UZgPwx7MyUVK4Vg82bfkC0wCk8QT/tthKo1WGRABYLrzECdGnNZN1tuWZL1GSgEoZSogb7ZUDkJ5DH+SCja0FE4ZItk3ufk8WBXUq26SdQz+wo1I+qxP5TyVwLbe1YfZler1aDsXyc0hgNDBvZta+Br4pROuMLUXEYHDFqWOMH8=,iv:9C+v3vj0O43yE6HMlqzNo06Bj0Mk4xXNglidPTU0iic=,tag:+QmNXJSgQlPzp7W6JIMCUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
