apiVersion: v1
kind: Secret
metadata:
    name: chatwoot-runtime-auth
    namespace: business
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:lT2zu+S61ueu9Awrt5oRDmcogF6ACAsul0qgicc6thu0Bet11kbeWODoyVV767TgQZEcIkzFBFVYwvmjkUlDU4CX7FS+4OerHQ7Cd6Eg8H08hJ3vHMEOTIM+vabhPywJf2Zf5sFFZc5bIU85gxfPmb+bhPnLe6brmk33dOEHim8=,iv:E0v9SnB3Kd+710+r4ZflYT1iYHcbvBtkwW2YUigiGVQ=,tag:zYXaKkg7aV/1lhiltaJJCQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+rCVJf8A0fw8xUikot36WTwwZbpwNki3xU2hw+8DdT6zoONfIfVclyiESuJb42fl9l2g8tp9AGz/K5C2BXj3lg==,iv:fFq/yqCtH/Z/8mq4z0LwPWdiwHBR52OGKnppl/bXrNo=,tag:njRfC8J92IQrYrGzp0c0QA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:DMkJap9NauarrbguFrOKzKFIC60rGj0vt84rlg0UR48=,iv:dZeKr4aW+WudaaCcN8iHHqKVd8UmMBIwBtlRxTaF4Tc=,tag:k6FmADZdSGqbJq5AUIS5jQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:YyBF0Nh8Zk5Z615NmNSamc0sFYEj49LW1Sf5XUcv/GxILk6q2+9/7iZLgc8SKLITGn8f5YLEstDaazW0eblcLLT7MpWRlilHicWJPgsR,iv:CwyaKH2aQYMrCvAT7DpyOTIkktq48rVc97gjMuYaTuo=,tag:y5UClcZTsmvtxwciEVAqEg==,type:str]
    STORAGE_ACCESS_KEY_ID: ENC[AES256_GCM,data:XY8+i3AXvDOMUsKu,iv:Xj2VkkuVpikRA0bUdQkNdsVkqev8aDv2wbqkUzKr+l8=,tag:g6zHmXeGdr36+oL3ONHwVw==,type:str]
    STORAGE_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:d2zDzQsc40zbbw+fB6TLrYb3WcVh0IZEunCZ6MSTdsbxEGFUb/TGfuDn5T9XEliulDMXqRhHfhz9uRIx1mWRuw==,iv:DVsq4MUpPI8EFQ0lCmSPCjA0nkeapTfEhzfoGa9Hi3I=,tag:htkez6n+Lg9kAqDdr81pTw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:lL6ZNdnNQVQ/PSBhbc9jZi5E9Ssrc51MOVb2/BwS8zA=,iv:D1AGxZyYrhoxnP/moRH4KxUJRCniEG7EeSJIcUGEzK8=,tag:63cxzC+mKaktETNn+6e6uw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:DrB9o1svxnwHtNm6V1yv1g==,iv:lQTVCcuxX+tt6/1HXT38C+GNz3AOz38/RMJBYyF6Cb4=,tag:/ib2ZLbfaiLqJ3oGXRgj0g==,type:str]
    MAILER_SENDER_EMAIL: ENC[AES256_GCM,data:AOh2SVQOouCLSrkMuRzW9gMS7nF76rD3yZJ12fu2IlLFpBenVRaVkfcqgQ==,iv:yI/OmQoBBmenC9RUah3xRKQgW7g1BCkALUZEngdUbT4=,tag:K+mCjIy/xfJnKCvgGBPKvA==,type:str]
    FB_APP_ID: ENC[AES256_GCM,data:2afg/Xy4eoieYu3+xuoouA==,iv:ht64JOyGcxHxvQDtA3wzKhbZ3JJHwSyT+wMpNuj/+uk=,tag:fwOttX47fcMglCAu19ZUDw==,type:str]
    FB_APP_SECRET: ENC[AES256_GCM,data:F/CO3ta4sDPm1GXIyVUEksamWhariXisYHwVqSNdN1c=,iv:3ejY8OBAZgdcMfJ9k0BS2o3HH6fFiLjnOdUWDmXRFRQ=,tag:YErkxTM7foCSXgb/Px2tyQ==,type:str]
    FB_VERIFY_TOKEN: ENC[AES256_GCM,data:epCnGxEsIIkn7CVr5RM32hs1AAsg6xTt/hvVNVkpvJM=,iv:Q8GA5MTAs1BFwJ6A79c32z558Tx6FKKDBIih8TCS29w=,tag:vUK++DuLCZ5y0k6rdQou1g==,type:str]
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS3hCb1JQYlFzbTdjbmtQ
            RUkxc0VtVHBwZnNmWTFHWVRsS1NMV2VQQ1VzCldrYjhCbjBRZEx6OHExaDN3RDly
            YUgxNUQwQTFJaHdCdTN6SUhqMDUrWVEKLS0tIEp0SjNiM21sRVoxOEE4YVlvZEJk
            a2p5NDlRQkpBRFZkZjdTZ21GV0d4dU0KsBxNLp4eesNAvTyd3NNtnHo5szSPVr/D
            zH6AiCZT2CUUxWpzX1Vf8T62tBL+AYCkgtClZzrZCNa+AFlOLUFLBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T02:07:57Z"
    mac: ENC[AES256_GCM,data:AfP8AXlybUIKHPnUSwzlGrfELJpMq5Z4AHJgXZPn8slrUDNTjKzVtGI2VdM+wEGrdDQ6y8cVvMpSaaOlFCGcLC2eCNlRLtb4bfG1Yoxv4KqmDFPHl9VI4ppcobw0JwGIeDxIGCjF7Dm61gwLuoja+JfmiTtgyiKtPmVx6a2WIsA=,iv:Cd8huMaxzmLuqmE08d4sQ9PHFIuz1qk9+8A4vbFj+n8=,tag:xQyKUDbgWzjyvzNQEG4WQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
