apiVersion: v1
kind: Secret
metadata:
    name: chatwoot-runtime-auth
    namespace: business
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:IWEsLPFr8U9gCnEJ3hI0nOljor+N2o/PdEBlAuRgn0kGMBfNLb8ZO3l6jgIMQig/oRBYuQ0wcEout0gV9ik5lEIJQU7okAZETN24+yFcCTQOI1/mv06J4627yKXrNJyA6hBNbSRfripFToq6DkDPGqy5gr2yGCkKxXEAJz8XqiA=,iv:3Slxur1VOOZYntrbvqKvtLQUHHm2+Uiq2UZxJSCvM/M=,tag:aa4ePP+tpk1sUEbmiQBC5w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:KTTROrZmG2cQ1ex2OW7V6p74I/cIq0ZbUM0QJKHaOXhQHreIpbRzVAjeIJZ5QYmoqVtMzEXhfweEFSPVB33G4Q==,iv:Iaqq/h6ZLZsx+VJ8IxauKK4tF6wv4cgZn4/E9PQ2CgQ=,tag:cTpIDy7f3Y4a2bX2wfScxQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:mZYR0kbWSXaJ/1vLY9LgfG8epiAYF6PWlbkF8pBIkbQ=,iv:nU4JREmVd3dWRZ5UF87Wl5kCCWKN29rwNy7mcnp1q/Y=,tag:Q7df4COyo83dmoaRBmZdHQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:1M5NwiGZooKHpSDueoE3I/1+s08ZA780NF8JXzMmiN1iw9BRaJ9zEsxhubWX0gmS3pBEVtbEMVhKzVkMjtB29etlXzbzG7A3b95vWZaS,iv:Z0QXAi6YGSqrGNyOO9xXfwq5SwQzmC0FdkwGczGQ6/U=,tag:RWN7e2PzcHdpICyrfoq/cQ==,type:str]
    STORAGE_ACCESS_KEY_ID: ENC[AES256_GCM,data:YtC2mVGiRGIa0u6c,iv:WajuBbfTbC5p/fY9TZy6/eB1yta9x6nCxaG2accd4qI=,tag:lTyyc2GPCvQyVq3CvNhkDw==,type:str]
    STORAGE_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4JHBt6RRM4cRMUH6vQt/n/Ab55h5pxsPaKNxj39Dt3KRlzPhxeiMannR16Ws9i8aqoF2ZmuNap2wqWBDj7gtIA==,iv:ffXVEbec4BYMb0SNScHx5+KkbnJn9V2gOSLpKWnC090=,tag:C4b/jzFJaQOqBnw7q7gz0Q==,type:str]
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5b3A4bTZVa2RZejlqQVVr
            eEtrVDNZQ1U5R3RiQkp4L01ya0xlL1Q0NkM0CkhaK3YxbEdYbjJQbGUvbCtGSCtV
            NFRvZy9sN1BZNno1dVgvWXVTN0xmMm8KLS0tIFc0bVdkbmFMdHVWQmR0K3dmdzYv
            U3IvWlZ4ZmFIQkYvd3pmQW8wdDU0MjAKJlkJvAq1v0vVoC3j+MSpB2KhHnQxrUis
            hYhaBt74w8ZUbaJJ0fK1SnZHbkTil0YnmlS9yw5yoAnrwZI4I7v5Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T23:43:24Z"
    mac: ENC[AES256_GCM,data:gyN/Nt7Y9nfUCL4/V+Ynut+FaOTVedvrtnfIF33T0D376kPLlDHZBjDde/svTrx6GZswyvKRGagaLrz/gadheatnAnAhGn6qxJtRKjcEkjeVDedalZklM5AhXKZ++YdnEQsuEU1XG/B40cq9xKjCQafNS8k39nNiZyWzskcYTkk=,iv:R1V80uu9xFsjvd8qPs6ym6qWCBIiDXCS8NmXoEtpDpE=,tag:Zo1qJ8xv9Cm9OviAQLnqbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
