apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evolution-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ingressClassName: traefik
  rules:
    - host: evolution.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evolution-api
                port:
                  number: 8080
