apiVersion: v1
kind: Secret
metadata:
    name: chatwoot-db-auth
    namespace: storage
type: Opaque
stringData:
    CHATWOOT_DB_USER: ENC[AES256_GCM,data:u37fx62Mp88eICtC,iv:1I4oRbro+qd0egWNdG5p1PKNdCyO4jOVIciEJC3pMEc=,tag:kBeyN2wxiDk1q8jnSlJlZA==,type:str]
    CHATWOOT_DB_PASSWORD: ENC[AES256_GCM,data:sloi0mVUZNpqAmSzmkOtjDF0En6+YWzigcWV8T8MDYCenxskfTQvD8A4cv8pEs662ev0cDVBXHx71hFOdoCYYg==,iv:BnFSrncUUhEwuw12pAMXiSJr5xamHBzvI8Y1S8T1qao=,tag:2FttOdv8n7zczohzxbQZPA==,type:str]
    CHATWOOT_DB_NAME: ENC[AES256_GCM,data:zTMVMdTzGeJEcfVzh3243Ywcsg==,iv:2u662NhhIUxYYo1Nn/UbVzZynKb1ElJR7i5eT4nlnhA=,tag:J9YEPwaJglA7aVNCPpHCNw==,type:str]
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBY0V3L0E5WHRTUVlPTUw5
            MGxjdnVoTERDZFd4TWV0Mnd3a0p3NEpydHlnCnhsNHNrM1VETHMzUFVKK1UvU0pB
            VHFZWVRyTFROL2loMEdkOFA2VGR4NUkKLS0tIEJTdTlDazVYOFpVaGVMRVBhQ3RM
            R214YVpHendwTmt1WXY4VTFXMlZWcUkKIi8haRYt/1722jV2WY9W00HBeczjHhYq
            +3ZypP/0ORTZjfhfaCDvzzL9a+9eOdmdpWG/DmY1+WKjvqlwSYLZKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T23:43:24Z"
    mac: ENC[AES256_GCM,data:uJVmhgdWIpGGcf6eWpCgEQYjND7JCGTZGqae8OLjObqTWv24OvyFphwnnlLelxKfRLTy77TZ0ds+ivfH1/41nQDMu/ZwEiVeWVfMJN7wGaYejZRpgcGoHLLaFbOa/zE8NPG8CIN7DrMx7UPmIu9Sh2DTb7yJbD+Wmyj+ou7Tv7g=,iv:AXD/hVX38BCqO8YhHWRkQoBtXGDPyaRJ5OV6nUuidJY=,tag:u8Duzt4+TCbSc5oGpzxDHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
