apiVersion: v1
kind: Secret
metadata:
    name: chatwoot-minio-auth
    namespace: storage
type: Opaque
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:LUBrMg0x48Iti+vv,iv:mSJ4FgZByfDBxN5MSeemLQCm3k++5tL5sVCrQoJe2lQ=,tag:Jk4e4zPxTmlXXuO42p1Icg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:kBHsIVlKdoGjq3Ff0qkWEgsIJQY/Srb38Xn3Tjrl7fUCucxIe3DesokLPas1g5DtM3JEUo66/q5MZlDy+KGVEg==,iv:40AkXq05hru6l6AZYW+KoSnZQtm9ePXp2GLw4XInTvc=,tag:TXHOT3UUVkrDESqbpFK35w==,type:str]
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSU9SOWVHYXZkTzJSL0d0
            aTN5Ymk1dzF6UnFiV2ZJclI0WmJQOElEcUI4CjNIRk9PaHhiWnZNbjE0UmcrdVpy
            cS8ySmY1aEh5VTBRMHo1K1ZCMXZIK1kKLS0tIGZGTFhybGlzNUN1bEgrUVpXb0o1
            Q0hCUi9aSXFzUkNKTGFTYmRyd3BmMHMKHb5qDqudBOEwnxSobs8w2YTJ7VIQ8eWY
            EVJN1imlg+DZdEf79NY+dFeHSYDeDh0TlbDw1ikDdZldYlGgcElPpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T23:43:24Z"
    mac: ENC[AES256_GCM,data:YI+mHFpgSZId/nxr169rVp6qXdC+fCnjQctBLSjQaME1+UizNGeOZtzKrwi1aqnTRhoq+EPC/SV9rja6LZeizXiv862QY8ULAqdxX9VmRQvx3/Ls0ouelfXlSJST1LQRsab7sLHgbc+TWyjrCA/UBvNOXtxLwFd/ZP14GuTXSgM=,iv:G7KzK4Qni4raYk+/VQRClJlFhSq3dPwwJYRtQEjQwZU=,tag:J7cphXfKAO/qY1FIhiuObg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
