apiVersion: v1
kind: Secret
metadata:
    name: evolution-db-auth
    namespace: storage
type: null
data:
    POSTGRES_DB: ENC[AES256_GCM,data:c3+oRRPquR4Zdcib3XfKPQ==,iv:MfcYiVxhRxGUUS9SjlGEty9I90qYbTtFrj0CNVJGnsw=,tag:6/IY7R8IlsiJaNM9xum7OA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:p8Y5XvTmfZOqFvk93yBsL0aRax+fqEjqnvRUTW25BTeSQAvp7YAFW+z9VqRuSVa88VAGZYvUguBMhjwANXtlEACib5VagWRJC0DLynYOc9tTXqcwyKEnEw==,iv:eVEqkKgC7XwE+eFJfFJnKfdd9sv/6ruXxfhmwmk/eTM=,tag:jAqniKBPJlNZJTY1ptDthw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:2XGR6mI+Hw2NSKP0Kwpopedfp4k=,iv:tCSUcE8xTRJ8rzcDGW+4cXtcD3pR3qoCLSYPBtCJDcI=,tag:wT7illhZY0wWOMzCCSFf9g==,type:str]
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUEFWcS9oaDc0TEczNDg3
            MXRheVFKd1BDVGRYK0xKaXJTNnhsUzdRYXlBCjB5Q1Fud3BpeU9McjhBQzVvWW1L
            TTRPSEZRdUdXUjgxTGsxZjltMGFCOUkKLS0tIFVIL2NOVXVHU0JJYi8zNW93MDNX
            WnkzQkt4SGxlZTJsaXFpVFlUS3Q4bmcKRWlbTGJemm0lV/i2G1f0CyxdUX/sLLqF
            30QXsBvzwB62d6WZGUCyfoYt+wT5/rDBF/U+sNL4ggJHZwYSjasYKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T14:29:32Z"
    mac: ENC[AES256_GCM,data:Dk1G2ErA1aq6BmxENRxNu+oxeWolD472b4tDYPEjpoeK/KDrmgAMrVXUuDDE6203V/dAhPjj7/YCMkz+6+z4MqnSrKcuw4Yg+lV6s0Ow/uc8ZJiLJ1fq6dS+ydCSIcPwP5riJjEOlZ2MqlfmVuo96ZumVKK+WZJzS5dz6P5tsTA=,iv:2ixFN/68lEaG341hTsj8hle2mW3BWHjfVeVQmHKh0AM=,tag:X1WqC1kr2wPZj4WbZi1EJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
