apiVersion: v1
kind: Secret
metadata:
    name: evolution-minio-auth
    namespace: storage
type: Opaque
data:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:lUNfpdRLKDcGgYmdGTXJ/6W9JLM=,iv:0YNn1M924HPx6lZgjAUVE9BD3c0mMR30VqeXBqw9DLI=,tag:vX083E8QqbLIZyVcdjxcGg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:/aPgAwd/L9QnRP/tRNuZRUqDpNcO3XWXtrJMYx3YvuqCKuLh/05Fdixr3l52eEteh5nVI2PyWvg=,iv:M/5OQTw9xgAK5TqNKvbPvZ6EAUpJm1D8yDiU/VKMbNE=,tag:FNxZ0KqdZkh5ETAGKnxbxQ==,type:str]
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWGNGMjBndXp6SlpmS1Zx
            NnY5d3c5TTBJZ281UnBpNjRPMzhvZ2ZEWHdVCnJTNzNGaFVQRVNiY2pCWFBUYmFy
            UHZGK2c3enJRNlRjWXo4N0s3WWxBemMKLS0tIDRBdWo1T1FMRDduR296TFBtWG1q
            RWp3NWtLU3gxaWx0eTdJTTlJNVo3OUkK1QVRjDn7EZCL6Myff1m1U8cZvxa7mD/d
            L3hrKX3pNk7s0qXLbKq48Pz9mrGCpidLB68IHelAOqOG2Dy9XMmKdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T15:24:21Z"
    mac: ENC[AES256_GCM,data:/nF0IjdMSEVnu+KFibCRX/M548PuPDunXKZieWVaSCkxGm4IwnZnsvPYrPtoy8PYqnRrgH0hqD0oNsALDBHu6Pi0c6ERT7r4ktaVH2YcuUEj5UDVzBksx12KBK8rM62SesBEK9d2ThezLlDlnDobh4htEf5qTL6VKdYKk4HUx4E=,iv:c7ySgi4yh7Xxb7aZ72EkLK3ISIN3jDSfdet0mmaGoHE=,tag:+VbsW6TRfmj/dP2NtZPYvA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.12.2
