apiVersion: v1
kind: Secret
metadata:
    name: minio-auth
    namespace: storage
type: Opaque
data:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:FQqAaZQihktcfoSvtAybCmL3HV60HBLOlSiebZkj3Jb1326UQTQelaTfBHg=,iv:oTay2QYpKzapl+88wG4+L1ynr9Pij8tRhU9ODnOOSjo=,tag:+tEPgQwX/v11WUFnntJMEA==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:IpnFiMnnOIBrs4O8Ej6Oww==,iv:uOGLaM/A15SowgWaWXrwGsZp55JeN8b0oA0BSBchDnA=,tag:xMkqdcBsLbzQTqYCFIHnrw==,type:str]
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YnFWYTZ6ZTFieFFuMjgr
            YTdsbjdYNFNoejRvUDJaKzFIUUd5ZStuSTFrCm9UZGRhclhFcDF0YjdjUVBNdjE4
            U3lOaW05N3hMZnhGa1VZTlp3UEhocHcKLS0tIHYrdWUzaFQrQ244Z0NPNFk4NFFM
            cjRkT2NwUDVMWFRIYXZZYnIwZEhvcWcKCa+el7NI8gr7ALeCHUgHvUIm4ytGNbhS
            03mHY2wYgCYjlaHWOX8i5ZvpntFdxs66zNGdDgj9ucPm13EEcZT7yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T13:59:04Z"
    mac: ENC[AES256_GCM,data:ktS0KgFwa4GEQBWPqHYykGthuysFr4PlGZO9pOl/ea73ZSR8rOOo97ws6TTgY7t80yQiSo2UTRAJJgquU4BovJr6Tm1FqGR88ZlkeNveqvt6gP5XXZnMvqDE0xiwNHAZce5TwDZD/OHk9BN2DH8VLdgluDkv+LpMFsL3DMlo9SE=,iv:zw2L+Uv9Qic3Px3d/JncAp4zQpDZXB5jPHcnmtIw29o=,tag:RlZ/dkvUK1XBZNN/Ospu2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
