apiVersion: v1
data:
    PGADMIN_DB_PASSWORD: ENC[AES256_GCM,data:UAnxgMEtr/IAsnZOhMXmGngsVA+S7e8xUbisEqNZ4cbxyrtqrZI5QN1KmnPLEwlUC8iDfBflmM2zdHzpa6uSgA==,iv:C3CsZAh/ecV+NwmfAJNEyNHJNgrMLciv/f3VdEAFEWE=,tag:Cq894XvL/A5gSisP5GoTTg==,type:str]
    PGADMIN_DB_USER: ENC[AES256_GCM,data:Cpast+m1ONcGxSsykV4MWpeYt6E=,iv:cvlfFAplg6uLijAydOuR8r8bfmCXuZX7pVVw+fSsBGE=,tag:3nhQXbrgnpb+ZszRX19ztw==,type:str]
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:aog+XZC9f79ZnPoKY8x7IxGb9eK9pOGeB7NqYEyKdvY=,iv:UKWWIqEq63eHYk7/vsVTCs06KJtiGHRtA5qbWXEGlQU=,tag:oM2WLUWbIuTCXxfasvYvUQ==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:XzYeAHV1jXjQuoLn5t278iNYKL2QhJqDqzuVKTcFxxny3/5ZAf6SVFW4qlmpHLw8Wceapr2cp2efqlNolFCu3w==,iv:ODfL5NZ2g8Giq+uDZbGWuqH7G1+uv4S44kwQMjpxkTs=,tag:zqMIf6Jlb32Li4glgl3Z/A==,type:str]
kind: Secret
metadata:
    name: pgadmin-auth
    namespace: storage
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMXB5amsvOEpCRm5LSlJI
            cGhzakpwVVdtL0hpTEY0b2ZNSjczaVIzc1YwCnI2ZXpkbkFlM2VKV3VGd3E1a095
            TEdBOW1CNTZ0a3RURGxobXBIYmFHSUkKLS0tIHlWSCt5WWNCL0ZxRDRkcTdkS2Fw
            QVh0bmZIYklvY0RRTVoxVS81Y24wMUkKN/ct6Yc0YZ9OgklrSniVhJz9ZBvu7jnU
            tSFxiHGy5HUWd5CnhzhXPGy0EpPQXfe8YmGlP/PxzHDmlpUSv0UY2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T16:10:03Z"
    mac: ENC[AES256_GCM,data:rBcGOeCTCNiLkWMHvF7KldAB/FgWHP6NoHOadcLB4AI1Ts/FaXptI3ORQjpSawu/DFvEhDbQ1p+4p0g+Ahl402bI/ZHmHaJv6fbQ9omr3v4YbpQPLl7OcZfoZ3i9DCkr7P1HT4MNly03cSUU8h+tPtsH6qIvnVirmamBfE28570=,iv:Cc8P+9GLJ61OKhOoXbVmH+ymWYtMunS9kIi+7yYhSf0=,tag:n0Hjp+ep+IvkHIrCGcjUuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
