apiVersion: v1
data:
    PGADMIN_DB_PASSWORD: ENC[AES256_GCM,data:QDTH1xJ4hyRL4UtSn5pTO8QiwmNyhvXwhyeDRNFP4WWXjISIMgLla3ZCsZ8sNa/unRdlouSyAqwR8qphl5TLog==,iv:uKJbPo7wsbdPSlR2l3GC539K7YM16xf5Xnf8FCPo5P8=,tag:+4kNR4zAtvdTRu7bvxGOkQ==,type:str]
    PGADMIN_DB_USER: ENC[AES256_GCM,data:LNJyn+cg2o5a+VBRGRWyPUcVaJI=,iv:/HD3K2y9ScpSUE/H7Dh0Ig0lJfO9GP0GHiVa0yAEdG8=,tag:tsFne1VJ9DZ/XxGgQjaWVQ==,type:str]
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:1UQIB23JCRZNcY+YCSzvG2m8sboNLYn/4y3tli/QZ5M=,iv:r37+gY1BQG7DMtPTb+nEHy81hoaYMWCC7yeHP3qMv4o=,tag:riHPQO/zxSSUglswS81Ykw==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:htXeq7xvNSE7EQf/bpT7S7Ptd75/xJb9qFkPeFDRdgOcxuZmA/iAoGhwPKgAyCemD/e2aZ3CYd3acEfodUFpbw==,iv:dlu3NkE4q81dE2CI0WMAnPr26GjHAh49SPhe4B7vFjg=,tag:f7cblllOskuCCZPDeVjI9A==,type:str]
    PGPASS_FILE: ENC[AES256_GCM,data:TbPuzPwdXZpZ1Nk50wKKzoe7lK3q0JM3BWwR6Sar6wcCmaG2HDfXwxOTQezcc48msr827ezKMgrbnrwsno0TnJY1dYDddmOTu4K8VyTSKmZIytedCljuo1Rbw2m1Fr/Xk0bjw4iPFpKxSXkp+/GCJc0P6PnRe4yndjge/sH6Sjh0Pa5kkSkGHzKLoKc=,iv:QAeYlpmqGRaCnH4Y+rQoOpGUvNd8ZR0QtgfOi6tbNJ0=,tag:vNRVeD9D/QJFPvIxS8bBjg==,type:str]
kind: Secret
metadata:
    name: pgadmin-auth
    namespace: storage
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocFFKTEJmWXVyWm9DNzFJ
            NW8vVG91SzNjbFNrYUk2ZHhYRWRQNzM4TVFBClFhS2J3ejVpR05tcVJoMmhVMmY5
            T1BsRzhkamt6YWp3MCtPdHhVTXhTclkKLS0tIHN5QURra1NmbWlERDZhWk1sakxK
            ZnJRRW5FRlZTaG1ycjA4V3RBemE3azAKG9w0OLMB86Bel4wdPU4ddlvSDMrqUaUh
            uKZmX1/scJ2UrGLUpme2rrVTK9H55HWVBWmNTYsJEMIGBm4CMaWrVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T16:24:09Z"
    mac: ENC[AES256_GCM,data:x0wl+//xqT4T3x/V4ic84GxO6Ch9avmRc57GXmEZWOyLppe4Qm5U78ciCv7/7iZZKK2cL6KlCh6213eGc2QguX6bCjOMxhB0C/78VBnTvruBikb0FvIGOPeUbyYhQ1NduOlDPSjeWPYdu/BNE3S5FKWTbZcTQZFMaR5XRExmb/c=,iv:pPYFxjzjngVHAtM8S5pwWufUrJcRjxkiPMPRsAKezZM=,tag:KHdC7oWz/i9SSv42yTg4yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
