apiVersion: v1
kind: Secret
metadata:
    name: pgbouncer-auth
    namespace: storage
type: null
data:
    PGBOUNCER_AUTH_PASSWORD: ENC[AES256_GCM,data:txSMl+uxA9SVc1Jh4fsnbiQZkCNXNMfvhfrKfHdSpZqjbFqJifev4GQrruEXmWW+ntGGWWtRKF4rSBMqcdRvoTI1uX/o12sNQWvPXAfr02xE9DVi/aNvgw==,iv:bEGm7y4S/j8NavH2b1YX+Keej/wE7THvrGaVFZ4AV/I=,tag:pQ6geTS6cyZbb2aB28Qbng==,type:str]
    PGBOUNCER_AUTH_USER: ENC[AES256_GCM,data:dRHnKb0FN8qQ+JDTIRvUG9zX2GE=,iv:b4CaQ+hZJSP10L8TXgJ6ZqDrdnSEImwmDu6Ac5ClDzc=,tag:ZA3rinaAgJBHh0t9NTTfOw==,type:str]
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMENWZlIxcEswVm1vS2Ir
            cEFDWkQyWUNISzF5SzFwZHVvaHA5SmdwYmhZClI1VzVGUnM2QUJ5ZGFpNTFVQ1Ay
            QU8vTnd6bmFkOHBsVzNOSVNhWVl6eU0KLS0tIGoxRWNWdEliVnZCWGpTZmpmMTkr
            UHVwdGQvcVJkcEVCWWxMVGJXVG9jbVUKn9BbWNHDz8JuKuAoaoLLWeqm0V7vtLF4
            EBjomVecTh/GgdzUW6eQMLf2yN6W4M7Nh73bUj3nrRjeS6/c68COlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T14:29:33Z"
    mac: ENC[AES256_GCM,data:1FtA4y2qVnhTrj24Dk7UKRMu1CKz7z8FJgg3HFOPkFtzmqzhWdLqVlk572utfLi9nMKYtbWrPfx2tSD5ca6z5yLwDRNN6A7KnSJs3z4h5sIKF/zZyVELg8qysukgsYh1Wvzk5TLiivNjcfijzul+BYaSMADAi7KUCDKIMgS2G6g=,iv:Nbfu5rRIYEKQbeqJHjNETPawGBVgRUFttsKRutrOzOI=,tag:xx2RpL0CrCsF4vZLiCUS5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
