apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: storage
type: Opaque
data:
    POSTGRES_DB: ENC[AES256_GCM,data:oOR5cH8NfTRytslv,iv:XhPJ3HZZOVUCUb22MF10xUOmHlIwtcrdnVMQ+4Ub/C8=,tag:OzeCyXiWDxBLJNUukyONbw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:YN0g6iNCa4xXepKworeMgMwaQUgwR4+KQ0okaDWdYWHzuM6+myXlBnB4RLAYkaLJXQqZbTVTcVVXj91V4rNVIn4gH81GaHjRdFODCu3jdwijiib2ccc8Lw==,iv:mR6V+AlxLTKTuNZzpMtlaOUwnCLGrlUVD7NFtwNIMJw=,tag:azLJNXajb6jyixsVCHa2Iw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Z2ON4bDQmvTjhrr9kPYXn9NHjnE=,iv:9zDsheDkASocLT7pw7scw443YLplYQdj493KXRpLnY0=,tag:1s0pTECt1rG3Y+tlBZYx9w==,type:str]
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3c0g1T2ZYWmkvd3BJZ09W
            RkF4aUhoZnQ0a2dTb1BCVDkxVzg2TG0xM0dNCmo1MG5UZGsvT3FUbjVUR0ZlWEdY
            QVR2TWdieHgwd01SQWo3cjBCMzVQY28KLS0tIDJoUS9JOHNqS05Ibm41WHdwY250
            SzhKUU9WSnkzWGIvOVBQWC9oQ0J3Q28KB/N6qmrBnhxigig6Ts0vLqwJ7QEkQDl2
            88qMmqVl9dNixaUe8Mss6Bs0JkMfc3ZytjaH0ru/Grpg1gTIlmyiLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T00:45:45Z"
    mac: ENC[AES256_GCM,data:6jTg+MW98p7++lk8vxE4AtiDSSYiBQsjUyPVqfJHV3S2PhVk+lp2gWCOrXl++Nf+sPY22IdqxCcK5+6/zGk4zj9x7QgBFnB1cqJ3rmU6wj1S1cMPVHKHapG/Ydt/6Uh4rw3U8PYxnzkZBGW1D8RJhCtLsB5xYzPPdEoCCHAkWr4=,iv:NioJw0521JWCbJCiiNR3ISroLj85O/cZsqiBxksNF1E=,tag:EF2mHp8IkbiEU7WxpzTlNA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
