apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: storage
type: Opaque
data:
    POSTGRES_DB: ENC[AES256_GCM,data:OX2VReYcmliNHcq0,iv:0foTlOmRL6b9JkQiZ7u+Lcfdm1DsRwHOr0UBU+F2lS8=,tag:04MXcnKpmDbAzCs0P7i+4w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:VgVvqcpWW6PNQkyehQQozhVESbq9pYK30dJHRdHHwNPYD4PyURz8U+dvqX8=,iv:hmOwa+qwF7uKtjnPv3AGaSTBn5eyRPwaNE2zMn1Yp2o=,tag:UU5hKwS5U0QAwtbdRWjrjg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:cuuVZomQNwdIZ9+eIDnz+GSIFFQ=,iv:M/n0X83SA9d0WQRnNht+zRCG0yh4Ih3hXtbhmghcRVY=,tag:QVeLwo5qHyky2H0PV6YlVQ==,type:str]
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbXZtbXZPeEtJNHJ4djN3
            MGJaaWRSVmZxcWI4SmJvZUl3eFp6Z2NJRHk4CmlyTC8wckZpcHhqWFZVVm9UZzNq
            QUVQUzRnSUZmS2ZJQ3BNOVF5NFF5MmsKLS0tIFhKcFplZ2hLWUZWY1RUR1BDRS9U
            K2RiV2d2aGx0emgvblJJdFN2U0ZGNkkKUxTPqWJ8Q3WkfFKQ6pTAIyA/sV1ZH9Bu
            V9DzeDOVJ7D3f3O3P6bxnwqkiz7IXhCSP68BGeZbrsnBTCb+XOoRdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T13:59:03Z"
    mac: ENC[AES256_GCM,data:+fC+D+SPsoKbwDWy3Tsj5Z+ruV31TfTTuoYKGcNXEg37l/FjO+scCfvyngSx38A2lN2yFsefe/w8ohCQjP0Sja0MV45TvKORtWYjPQsXn8Qtcm03pSofSqEM7JXRy4P4MeA50mpaxbE18fYXXat0yZvCMBqnrOpXmxAp96A7lcc=,iv:55JwE6wOJHtdaCA7Qa4WzLN+YlF3dGVbGl6vQnkGw88=,tag:JJyj/xz2uVpOHCmN3cGCSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
