apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: storage
type: Opaque
data:
    REDIS_PASSWORD: ENC[AES256_GCM,data:c7LJU459ZazQmkvptSCsSozUPgpEhWNoxa6J1vllx6uxd52HY4T5n5G0gOE=,iv:D5Dcdx7DdtOU/bK2Zh5MvVc+9Lb7p1tYzIXy7Zxca38=,tag:P2IwzEwUhHwSG/0crxXJpw==,type:str]
sops:
    age:
        - recipient: age1t32sy2fqrnypka7na6qt7qw8l6g9j8aepvfqsmvnf3a8xjugvdhqjqhfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbldoRE1rTWRWTmFtRG1Y
            TEw5YkJnZDUyNER6UGFLS0pkZkJCSDRKQXhvCkswSklMOHkzTHcvb1NvVHdhdG96
            L0k1eE9DdmhnYXVOMjFCc2xXOENpNXcKLS0tIEJZZXdCQ1FvMmRyWmh2NDloWDFR
            TTJTWmNFN3lEeFAzbzRSMGRNMDBDb0UKLWTqztCZbUIezCDsRFAxqW03JmzhRJ33
            bgkCkAinnwVj/gAhM78KEPGwx3x1315jHRl97OnYfAJOTUc/BFJ7xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T13:59:04Z"
    mac: ENC[AES256_GCM,data:1y3p2u3Y8k2nx+H4qvdFd2dDIo9XbGkKpQmrKl2V8wds/C0ACjYKk2q8JN0WCwrMt07IDnoEoFWG5Scv8bRJfrKszVgwYPvbyTWSfYvaNhakR0W1bGT4juRuu+2cIQ0FWYhrbjoYas63OK7CNtalYScvo3YJtO184AXR9UjtY7E=,iv:LonLDIicGzTzrMrq4gX8vkslnzvlwkQ3i9zLfLtyYjc=,tag:LH8r7c37IogiC0DpEUQRHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
