server:
  fullnameOverride: victoria-metrics
  mode: statefulSet
  replicaCount: 1

  retentionPeriod: 15d

  persistentVolume:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  scrape:
    enabled: true
    config:
      global:
        scrape_interval: 15s
      scrape_configs: []
    extraScrapeConfigs:
      - job_name: kube-state-metrics
        honor_labels: true
        static_configs:
          - targets:
              - kube-state-metrics.monitoring.svc.cluster.local:8080

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

  extraArgs:
    loggerFormat: json
