server:
  fullnameOverride: victoria-metrics
  mode: statefulSet
  replicaCount: 1

  retentionPeriod: 15d

  persistentVolume:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  scrape:
    enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

  extraArgs:
    loggerFormat: json

  extraScrapeConfigs:
    - job_name: 'kube-state-metrics'
      honor_labels: true
      metrics_path: '/metrics'
      kubernetes_sd_configs:
        - role: service
          namespaces:
            names:
              - monitoring
      relabel_configs:
        - action: keep
          source_labels: [__meta_kubernetes_service_name]
          regex: kube-state-metrics
