apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage

resources:
  - minio-ingress.yaml
  - pgadmin-ingress.yaml
  - pgadmin.yaml
  - postgres.yaml
  - database-bootstrap.yaml
  - pgbouncer.yaml
  - redis.yaml
  - minio.yaml
  - minio-evolution-policy.yaml
  - minio-evolution-bootstrap.yaml
  - chatwoot-database-bootstrap.yaml
  - chatwoot-minio-policy.yaml
  - chatwoot-minio-bootstrap.yaml

generators:
  - secret-generator.yaml
