apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-evolution-policy
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "EvolutionBucket",
          "Effect": "Allow",
          "Action": [
            "s3:GetBucketLocation",
            "s3:ListBucket",
            "s3:ListBucketMultipartUploads"
          ],
          "Resource": [
            "arn:aws:s3:::evolution-media"
          ]
        },
        {
          "Sid": "EvolutionObjects",
          "Effect": "Allow",
          "Action": [
            "s3:GetObject",
            "s3:PutObject",
            "s3:DeleteObject",
            "s3:AbortMultipartUpload",
            "s3:ListMultipartUploadParts"
          ],
          "Resource": [
            "arn:aws:s3:::evolution-media/*"
          ]
        }
      ]
    }
